/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/qaIFEp8NcS5
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Card, CardHeader, CardTitle, CardContent, CardFooter } from "@/components/ui/card"
import { Switch } from "@/components/ui/switch"
import { Label } from "@/components/ui/label"
import { Progress } from "@/components/ui/progress"
import { Button } from "@/components/ui/button"

export default function Component() {
  return (
    <div className="flex justify-center items-center min-h-screen bg-background">
      <Card className="w-full max-w-sm p-4 bg-card text-card-foreground rounded-lg shadow-lg">
        <CardHeader className="pb-4">
          <div className="flex justify-between items-center">
            <CardTitle className="text-2xl font-bold">Dex Aimbot</CardTitle>
            <div className="flex items-center space-x-2">
              <Switch id="enabled" defaultChecked className="bg-primary" />
              <Label htmlFor="enabled" className="text-primary">
                Enabled
              </Label>
            </div>
          </div>
        </CardHeader>
        <CardContent className="space-y-4">
          <p>Dex Aimbot is a modern and professional cheat with a 5% aimbot function.</p>
          <div className="space-y-2">
            <Label htmlFor="aimbot-strength" className="text-base font-medium">
              Aimbot Strength
            </Label>
            <div className="flex items-center space-x-2">
              <span className="text-primary">5%</span>
              <Progress value={5} className="w-full bg-muted rounded-full" />
            </div>
          </div>
          <div className="space-y-2">
            <Label htmlFor="recoil-control" className="text-base font-medium">
              Recoil Control
            </Label>
            <div className="flex items-center space-x-2">
              <span className="text-primary">5%</span>
              <Progress value={5} className="w-full bg-muted rounded-full" />
            </div>
          </div>
        </CardContent>
        <CardFooter>
          <Button className="w-full bg-primary text-primary-foreground rounded-md shadow-md hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2">
            Apply
          </Button>
        </CardFooter>
      </Card>
    </div>
  )
}
