/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/LYUyE0qrogM
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { useState } from "react"

export function Component() {
  const [recoilEnabled, setRecoilEnabled] = useState(false)
  return (
    <div className="flex flex-col items-center justify-center min-h-screen bg-gradient-to-br from-[#1a1b1e] to-[#2c2d31]">
      <div className="bg-[#1f2023] rounded-lg shadow-lg p-8 w-full max-w-md">
        <div className="flex items-center justify-between mb-6">
          <h1 className="text-2xl font-bold text-[#e6e6e6]">Dex Aimbot</h1>
          <div className="flex items-center space-x-2">
            <div className="w-3 h-3 rounded-full bg-[#4caf50]" />
            <span className="text-sm text-[#4caf50]">Enabled</span>
          </div>
        </div>
        <div className="mb-6">
          <p className="text-[#b3b3b3] text-sm">
            Dex Aimbot is a modern and professional cheat with a 5% aimbot function.
          </p>
        </div>
        <div className="flex items-center justify-between mb-6">
          <span className="text-[#b3b3b3] text-sm">Aimbot Strength</span>
          <div className="flex items-center space-x-2">
            <span className="text-[#e6e6e6] text-sm">5%</span>
            <div className="w-20 h-2 bg-[#3a3b3e] rounded-full">
              <div className="w-[20%] h-full bg-[#4caf50] rounded-full" />
            </div>
          </div>
        </div>
        <div className="flex items-center justify-between mb-6">
          <span className="text-[#b3b3b3] text-sm">Recoil Control</span>
          <div className="flex items-center space-x-2">
            <div
              className={`w-5 h-5 rounded-full ${
                recoilEnabled ? "bg-[#4caf50] flex items-center justify-center" : "bg-[#3a3b3e]"
              }`}
              onClick={() => setRecoilEnabled(!recoilEnabled)}
            >
              {recoilEnabled && <div className="w-3 h-3 rounded-full bg-[#1f2023]" />}
            </div>
          </div>
        </div>
        <div className="flex justify-end">
          <button className="px-6 py-2 rounded-full text-sm font-medium bg-[#4caf50] text-[#1f2023] hover:bg-[#43a047]">
            Apply
          </button>
        </div>
      </div>
    </div>
  )
}
