/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/tG8q7IBGATK
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card"
import { Switch } from "@/components/ui/switch"

export function XDXD() {
  return (
    <div className="flex flex-col w-full min-h-screen bg-background">
      <header className="flex items-center h-16 px-4 border-b shrink-0 md:px-6">
        <h1 className="text-lg font-semibold">Cheat Sheet</h1>
      </header>
      <main className="flex-1 overflow-auto p-4 md:p-6">
        <div className="grid gap-6">
          <Card>
            <CardHeader>
              <CardTitle>Cheats</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid gap-4">
                <div className="flex items-center justify-between">
                  <span className="text-sm font-medium">God Mode</span>
                  <Switch id="god-mode" />
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-sm font-medium">Infinite Ammo</span>
                  <Switch id="infinite-ammo" />
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-sm font-medium">Unlock All Levels</span>
                  <Switch id="unlock-all-levels" />
                </div>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Mods</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid gap-4">
                <div className="flex items-center justify-between">
                  <span className="text-sm font-medium">Unlimited Health</span>
                  <Switch id="unlimited-health" />
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-sm font-medium">Increased Damage</span>
                  <Switch id="increased-damage" />
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-sm font-medium">Faster Movement</span>
                  <Switch id="faster-movement" />
                </div>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Secrets</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid gap-4">
                <div className="flex items-center justify-between">
                  <span className="text-sm font-medium">Unlock Hidden Levels</span>
                  <Switch id="unlock-hidden-levels" />
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-sm font-medium">Reveal All Collectibles</span>
                  <Switch id="reveal-all-collectibles" />
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-sm font-medium">Activate Developer Mode</span>
                  <Switch id="activate-developer-mode" />
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      </main>
      <footer className="bg-muted p-4 text-center text-sm text-muted-foreground">
        <h2 className="text-lg font-semibold mb-2">Cheat Sheet</h2>
        <p>Activate cheats, mods, and secrets</p>
      </footer>
    </div>
  )
}
